name: Build Python Package

on:
  push:
    branches:
      - add-pypi-package

jobs:
  ubuntu-multiple-pythons:
    name: Build Wheels on Ubuntu 20.04
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      name: Checkout the repository
      with:
        submodules: recursive
    - name: Build wheels
      uses: pypa/cibuildwheel@v1.12.0
      with:
        package-dir: interfaces/cython
      env:
        CIBW_BUILD: cp36-* cp37-* cp38-* cp39-*
        CIBW_SKIP: "*-win32 *-manylinux_i686"
        CIBW_BEFORE_ALL_LINUX: "yum install -y boost-devel && python -m pip install scons cython numpy && python `which scons` build -j2"
    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_TOKEN }}
        packages_dir: wheelhouse/
        repository_url: https://test.pypi.org/legacy/
