name: Build Python Package

on:
  push:
    branches:
      - add-pypi-package

jobs:
  ubuntu-multiple-pythons:
    name: Build Wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2019, ubuntu-20.04, macos-10.15]
      fail-fast: false
    env:
      BOOST_ROOT: ${{ github.workspace }}/3rdparty/boost
      BOOST_URL: https://pilotfiber.dl.sourceforge.net/project/boost/boost/1.75.0/boost_1_75_0.7z
    steps:
    - uses: actions/checkout@v2
      name: Checkout the repository
      with:
        submodules: recursive
    - name: Install Brew dependencies
      run: brew install boost
      if: runner.os == 'macOS'
    - name: Restore Boost cache
      if: runner.os == 'Windows'
      uses: actions/cache@v2
      id: cache-boost
      with:
        path: ${{env.BOOST_ROOT}}
        key: boost
    - name: Install Boost Headers
      if: steps.cache-boost.outputs.cache-hit != 'true' && runner.os == 'Windows'
      run: |
        BOOST_ROOT=$(echo $BOOST_ROOT | sed 's/\\/\//g')
        mkdir -p $BOOST_ROOT
        curl --progress-bar --location --output $BOOST_ROOT/download.7z $BOOST_URL
        7z -o$BOOST_ROOT x $BOOST_ROOT/download.7z -y -bd boost_1_75_0/boost
        mv $BOOST_ROOT/boost_1_75_0/boost $BOOST_ROOT/boost
        rm $BOOST_ROOT/download.7z
      shell: bash
    - name: Build wheels
      uses: pypa/cibuildwheel@v1.12.0
      with:
        package-dir: interfaces/cython
      env:
        CIBW_BUILD: cp36-* cp37-* cp38-* cp39-*
        CIBW_SKIP: "*-win32 *-manylinux_i686"
        CIBW_BEFORE_ALL_LINUX: "yum install -y boost-devel && python -m pip install scons cython numpy && python `which scons` build -j2"
        CIBW_BEFORE_ALL_MACOS: "python3 -m pip install scons cython numpy && python3 `which scons` build -j2"
        CIBW_BEFORE_ALL_WINDOWS: "python3 -m pip install scons cython numpy && scons build boost_inc_dir=%BOOST_ROOT% f90_interface=n -j2"
        CIBW_ARCHS_MACOS: "x86_64 arm64"
        CIBW_ARCHS_LINUX: "auto64 aarch64"
        CIBW_ENVIRONMENT: "GITHUB_WORKSPACE=${GITHUB_WORKSPACE} BOOST_ROOT=${BOOST_ROOT}"
    - name: pypi-publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_TOKEN }}
        packages_dir: wheelhouse/
        repository_url: https://test.pypi.org/legacy/
